name: Sync to Gitee
on:
  push:
    branches:
      - main  # 监听 main 分支的更新

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Push to Gitee
        run: |
          git remote add gitee ${{ secrets.GITEE_REPO_URL }}
          git push -f gitee main  # 强制推送，确保同步
